/**
 * 浏览器全局对象
 * @type {string[]}
 */
var descriptor = {
    'window':{
        'type': 'Window',
        'id': 'object',
    },
    'Window': {
        'type': 'Window',
        'id': 'class',
        'inherit':'EventDispatcher',
        'static': {
            'setInterval': {type: 'int', id: 'function', param: ['Function', 'Number']},
            'clearInterval': {type: 'Boolean', id: 'function', param: ['Number']},
            'setTimeout': {type: 'int', id: 'function', param: ['Function', 'Number']},
            'clearTimeout': {type: 'Boolean', id: 'function', param: ['Number']},
            'alert': {type: 'void', id: 'function', param: ['*']},
            'confirm': {type: 'Boolean', id: 'function', param: ['*']},
            'blur': {type: 'void', id: 'function', param: []},
            'close': {type: 'void', id: 'function', param: []},
            'confirm': {type: 'Boolean', id: 'function', param: ['String']},
            'createPopup': {type: 'void', id: 'function', param: ['*']},
            'focus': {type: 'void', id: 'function', param: []},
            'moveBy': {type: 'void', id: 'function', param: ['int', 'int']},
            'moveTo': {type: 'void', id: 'function', param: ['int', 'int']},
            'open': {type: 'void', id: 'function', param: ['[String]', '[String]', '[String]', '[String]']},
            'print': {type: 'void', id: 'function', param: []},
            'prompt': {type: 'void', id: 'function', param: ['[String]', '[String]']},
            'resizeBy': {type: 'void', id: 'function', param: ['int', 'int']},
            'resizeTo': {type: 'void', id: 'function', param: ['int', 'int']},
            'scrollBy': {type: 'void', id: 'function', param: ['int', 'int']},
            'scrollTo': {type: 'void', id: 'function', param: ['int', 'int']},
            'frames': {type: 'Array', 'id': 'const'},
            'closed': {type: 'Boolean', 'id': 'const'},
            'defaultStatus': {type: 'String', 'id': 'const'},
            'document': {type: 'Document', 'id': 'const'},
            'history': {type: 'history', 'id': 'const'},
            'innerheight': {type: 'uint', 'id': 'const'},
            'innerwidth': {type: 'uint', 'id': 'const'},
            'innerwidth': {type: 'uint', 'id': 'const'},
            'length': {type: 'int', 'id': 'const'},
            'location': {type: 'location', 'id': 'const'},
            'name': {type: 'String', 'id': 'var'},
            'navigator': {type: 'navigator', 'id': 'const'},
            'opener': {type: 'window', 'id': 'const'},
            'outerheight': {type: 'uint', 'id': 'const'},
            'outerwidth': {type: 'uint', 'id': 'const'},
            'pageXOffset': {type: 'int', 'id': 'const'},
            'pageYOffset': {type: 'int', 'id': 'const'},
            'parent': {type: 'window', 'id': 'const'},
            'screen': {type: 'screen', 'id': 'const'},
            'self': {type: 'window', 'id': 'const'},
            'status': {type: 'String', 'id': 'const'},
            'top': {type: 'window', 'id': 'const'},
            'screenX': {type: 'int', 'id': 'const'},
            'screenY': {type: 'int', 'id': 'const'},
        }
    },
    'document':{
        'type': 'Document',
        'id': 'object',
    },
    'Document': {
        'type': 'Document',
        'id': 'class',
        'static': {
            'all': {type: 'Array', 'id': 'const'},
            'anchors': {type: 'Array', 'id': 'const'},
            'applets': {type: 'Array', 'id': 'const'},
            'forms': {type: 'Array', 'id': 'const'},
            'images': {type: 'Array', 'id': 'const'},
            'links': {type: 'Array', 'id': 'const'},
            'head': {type: 'Node', 'id': 'const'},
            'body': {type: 'Node', 'id': 'const'},
            'documentElement':{type: 'Node', 'id': 'const'},
            'cookie': {type: 'String', 'id': 'var'},
            'domain': {type: 'String', 'id': 'const'},
            'lastModified': {type: 'String', 'id': 'const'},
            'referrer': {type: 'String', 'id': 'const'},
            'title': {type: 'String', 'id': 'var'},
            'URL': {type: 'String', 'id': 'const'},
            'close': {type: 'void', 'id': 'function', param: []},
            'getElementById': {type: 'Node', 'id': 'function', param: ['String']},
            'getElementsByName': {type: 'Node', 'id': 'function', param: ['String']},
            'getElementsByTagName': {type: 'Node', 'id': 'function', param: ['String']},
            'createDocumentFragment': {type: 'Node', 'id': 'function', param: []},
            'createElement': {type: 'Node', 'id': 'function', param: ['String']},
            'open': {type: 'void', 'id': 'function', param: []},
            'write': {type: 'void', 'id': 'function', param: ['...']},
            'writeln': {type: 'void', 'id': 'function', param: ['...']},
        }
    },
    'navigator ': {
        'type': 'Object',
        'id': 'object',
        'static': {
            'plugins': {type: 'Array', 'id': 'const'},
            'appCodeName': {type: 'Boolean', 'id': 'const'},
            'appMinorVersion': {type: 'String', 'id': 'const'},
            'appName': {type: 'Document', 'id': 'const'},
            'appVersion': {type: 'history', 'id': 'const'},
            'browserLanguage': {type: 'Number', 'id': 'const'},
            'cookieEnabled': {type: 'Number', 'id': 'const'},
            'cpuClass': {type: 'Number', 'id': 'const'},
            'onLine': {type: 'Number', 'id': 'const'},
            'platform': {type: 'String', 'id': 'const'},
            'systemLanguage': {type: 'String', 'id': 'const'},
            'userAgent': {type: 'String', 'id': 'const'},
            'userLanguage': {type: 'String', 'id': 'const'},
            'javaEnabled': {type: 'Boolean', 'id': 'function', param: []},
            'taintEnabled': {type: 'Boolean', 'id': 'function', param: []},
        }
    },
    'location': {
        'type': 'Object',
        'id': 'object',
        'static': {
            'hash': {type: 'String', 'id': 'const'},
            'host': {type: 'String', 'id': 'const'},
            'hostname': {type: 'String', 'id': 'const'},
            'href': {type: 'String', 'id': 'const'},
            'pathname': {type: 'String', 'id': 'const'},
            'port': {type: 'int', 'id': 'const'},
            'protocol': {type: 'String', 'id': 'const'},
            'search': {type: 'String', 'id': 'const'},
            'assign': {type: 'void', 'id': 'function', param: []},
            'reload': {type: 'void', 'id': 'function', param: []},
            'replace': {type: 'void', 'id': 'function', param: []},
        }
    },

    "NodeList": {
        'type': 'NodeList',
        'id': 'object',
        'inherit': 'Object',
        'proto': {
            "length": {type: "int", id: "const"},
            "item": {type: "Node", id: "function", param: ["int"], required:[true]}
        }
    },

    'Node': {
        'type': 'Node',
        'id': 'class',
        'inherit': 'EventDispatcher',
        'proto': {
            'text':{type: 'String', 'id': 'var'},
            'content':{type: 'String', 'id': 'var'},
            'textContent':{type: 'String', 'id': 'var'},
            'innerHTML':{type: 'String', 'id': 'var'},
            "hasChildNodes":{type: 'Boolean', 'id': 'function',param: []},
            "childNodes":{type: 'NodeList', 'id': 'const',param: []},
            "removeChild":{type: 'Node', 'id': 'function',param: []},
            "appendChild":{type: 'Node', 'id': 'function',param: ['Node']},
            "replaceChild":{type: 'Node', 'id': 'function',param: ['Node',"Node"]},
            "insertBefore":{type: 'Node', 'id': 'function',param: ['Node','*']},
            "setAttribute":{type: 'void', 'id': 'function',param: ['String',"*"]},
            "getAttribute":{type: '*', 'id': 'function',param: ['String']},
            "parentNode":{type: 'Node', 'id': 'const'},
            "replaceChild":{type: 'Node', 'id': 'function',param: ['Node','Node']},
            "className":{type: 'String', 'id': 'var'},
        }
    },
    'HTMLElement': {
        'type': 'HTMLElement',
        'id': 'class',
        'inherit': 'Node',
        'proto': {
            'getElementByName': {type: 'Array', 'id': 'function', param: ['String']},
            'getElementById': {type: 'Node', 'id': 'function', param: ['String']},
            'addChild': {type: 'Node', 'id': 'function', param: ['Node']},
            'addChildAt': {type: 'Node', 'id': 'function', param: ['Node','int']},
        }
    },
    'Element': {
        'type': 'Element',
        'id': 'class',
        'inherit':'EventDispatcher',
        'static':{
          'querySelector':{type: 'Array', 'id': 'function', param:['String'] },
          'createElement':{type: 'Node', 'id': 'function', param:['String'] },
          'getNodeName': {type: 'String', id: 'function', param: ['Object']},
          'getWindow': {type: 'Object', id: 'function', param: ['Object']},
          'isFrame': {type: 'Boolean', id: 'function', param: ['Object']},
          'isDocument': {type: 'Boolean', id: 'function', param: ['Object']},
          'isWindow': {type: 'Boolean', id: 'function', param: ['Object']},
          'isEventElement': {type: 'Boolean', id: 'function', param: ['Object']},
          'isHTMLContainer': {type: 'Boolean', id: 'function', param: ['Object']},
          'isNodeElement': {type: 'Boolean', id: 'function', param: ['Object']},
          'isForm': {type: 'Boolean', id: 'function', param: ['Object']},
          'isHTMLElement': {type: 'Boolean', id: 'function', param: ['Object']},
          'contains': {type: 'Boolean', id: 'function', param: ['Object','Object']},
          'equal': {type: 'Boolean', id: 'function', param: ['Object','Object']},
          'isAnimationSupport': {type: 'Boolean', id: 'function', param: []},
          'createAnimationStyleSheet': {type: 'Boolean', id: 'function', param: ["String","Object"]},
          'addStyleSheet': {type: 'Boolean', id: 'function', param: ["String","Object"]},
        },
        'proto': {
            'forEach': {type: '*', 'id': 'function',param:['Function']},
            'property': {type: 'String', 'id': 'function',param:['String']},
            'hasProperty': {type: 'Boolean', 'id': 'function',param:['String']},
            'properties': {type: 'Object', 'id': 'function',param:['Object'],required:[false]},
            'html': {type: 'String', 'id': 'function',param:['*'],'isFunAccessor':true},
            'text': {type: 'String', 'id': 'function',param:['String'],'isFunAccessor':true},
            'length': {type: 'int', 'id': 'const'},
            'slice': {type: 'Array', 'id': 'function', param:[] },
            'splice': {type: 'Array', 'id': 'function', param:['int','int'] },
            'concat': {type: 'Array', 'id': 'function', param:[] },
            'style': {type: '*', 'id': 'function', param:["String"] },
            'width': {type: 'uint', 'id': 'function', param:['uint'],'isFunAccessor':true },
            'height': {type: 'uint', 'id': 'function', param:['uint'],'isFunAccessor':true},
            'animation': {type: 'Element', 'id': 'function', param:["String"]},
            'scrollTop': {type: 'int', 'id': 'function', param:['int'],'isFunAccessor':true },
            'scrollLeft': {type: 'int', 'id': 'function', param:['int'],'isFunAccessor':true },
            'scrollWidth': {type: 'int', 'id': 'function', param:[],'isFunAccessor':true },
            'scrollHeight': {type: 'int', 'id': 'function', param:[] ,'isFunAccessor':true},
            'top': {type: 'int', 'id': 'function', param:[],'isFunAccessor':true },
            'right': {type: 'int', 'id': 'function', param:[],'isFunAccessor':true },
            'bottom': {type: 'int', 'id': 'function', param:[],'isFunAccessor':true },
            'left': {type: 'int', 'id': 'function', param:[],'isFunAccessor':true},
            'current': {type: 'Object', 'id': 'function', param:[] },
            'find': {type: 'Element', 'id': 'function', param:['Object'] },
            'parent': {type: 'Element', 'id': 'function', param:[] },
            'parents': {type: 'Element', 'id': 'function', param:[] },
            'prevAll': {type: 'Element', 'id': 'function', param:[] },
            'prev': {type: 'Element', 'id': 'function', param:[] },
            'nextAll': {type: 'Element', 'id': 'function', param:[] },
            'next': {type: 'Element', 'id': 'function', param:[] },
            'siblings': {type: 'Element', 'id': 'function', param:[] },
            'children': {type: 'Element', 'id': 'function', param:[] },
            'getChildAt': {type: 'Object', 'id': 'function', param:['int'] },
            'getChildIndex': {type: 'int', 'id': 'function', param:['Object'] },
            'addChild': {type: 'Object', 'id': 'function', param:['Object'] },
            'addChildAt': {type: 'Object', 'id': 'function', param:['Object','int'] },
            'removeChildAt':{type: 'Object', 'id': 'function', param:['int'] },
            'removeChild':{type: 'Object', 'id': 'function', param:['Object'] },
            'removeClass':{type: 'Element', 'id': 'function', param:['String'] , required:[false]},
            'addClass':{type: 'Element', 'id': 'function', param:['String'] },
            'hasClass':{type: 'Boolean', 'id': 'function', param:['String'] },
            'show':{type: 'Element', 'id': 'function', param:[] },
            'hide':{type: 'Element', 'id': 'function', param:[] },
            'getBoundingRect':{type: 'Object', 'id': 'function', param:['Boolean'] },
            'localToGlobal':{type: 'Object', 'id': 'function', param:['int','int'] },
            'globalToLocal':{type: 'Object', 'id': 'function', param:['int','int'] },
            'isNodeInDocumentChain':{type: 'Boolean', 'id': 'function', param:[] },
            'isEmpty':{type: 'Boolean', 'id': 'function', param:[] },
            'fadeIn':{type: 'Element', 'id': 'function', param:['float','float'], required:[false,false] },
            'fadeOut':{type: 'Element', 'id': 'function', param:['float','float'] , required:[false,false]},
        }

    },
    'StyleEvent':{
        'id':'class', 'type':'StyleEvent','inherit':'PropertyEvent',
        'static':{
            "CHANGE":{'id':'const','type':'String'},
        },
        'proto':{
            "property":{'id':'const','type':'String'},
            "newValue":{'id':'const','type':'Object'},
            "oldValue":{'id':'const','type':'Object'},
        }
    },
    'PropertyEvent':{
        'id':'class', 'type':'PropertyEvent','inherit':'Event',
        'static':{
            "CHANGE":{'id':'const','type':'String'},
        },
        'proto':{
            "property":{'id':'var','type':'String'},
            "newValue":{'id':'var','type':'Object'},
            "oldValue":{'id':'var','type':'Object'},
        }
    },
    'ElementEvent':{
        'id':'class', 'type':'ElementEvent','inherit':'Event',
        'static':{
            "ADD":{'id':'const','type':'String'},
            "REMOVE":{'id':'const','type':'String'},
            "CHANGE":{'id':'const','type':'String'},
            "ADD_TO_DOCUMENT":{'id':'const','type':'String'},
        },
        'proto':{
            "parent":{'id':'var','type':'Object'},
            "child":{'id':'var','type':'Object'},
            "type":{'id':'const','type':'String'},
        }
    },
    'MouseEvent':{
        'id':'class', 'type':'MouseEvent','inherit':'Event',
        'static':{
            "MOUSE_DOWN":{'id':'const','type':'String'},
            "MOUSE_UP":{'id':'const','type':'String'},
            "MOUSE_OVER":{'id':'const','type':'String'},
            "MOUSE_OUT":{'id':'const','type':'String'},
            "MOUSE_OUTSIDE":{'id':'const','type':'String'},
            "MOUSE_MOVE":{'id':'const','type':'String'},
            "MOUSE_WHEEL":{'id':'const','type':'String'},
            "CLICK":{'id':'const','type':'String'},
            "DBLCLICK":{'id':'const','type':'String'},
            "MOUSE_OVER":{'id':'const','type':'String'},
        },
        'proto':{
            "pageX":{'id':'const','type':'int'},
            "pageY":{'id':'const','type':'int'},
            "offsetX":{'id':'const','type':'int'},
            "offsetY":{'id':'const','type':'int'},
            "screenX":{'id':'const','type':'int'},
            "screenY":{'id':'const','type':'int'},
            "wheelDelta":{'id':'const','type':'int'},
        }
    },
    'KeyboardEvent':{
        'id':'class', 'type':'KeyboardEvent','inherit':'Event',
        'static':{
            "KEY_PRESS":{'id':'const','type':'String'},
            "KEY_UP":{'id':'const','type':'String'},
            "KEY_DOWN":{'id':'const','type':'String'},
        },
        'proto':{
            "keycode":{'id':'const','type':'int'},
        }
    },
    'ScrollEvent':{
        'id':'class', 'type':'ScrollEvent','inherit':'PropertyEvent',
    },

    'TouchEvent':{
        'id':'class', 'type':'TouchEvent','inherit':'MouseEvent','notCheckType':true,
        'static':{
            "TOUCH_START":{'id':'const','type':'String'},
            "TOUCH_MOVE":{'id':'const','type':'String'},
            "TOUCH_END":{'id':'const','type':'String'},
            "TOUCH_CANCEL":{'id':'const','type':'String'},
            "setting": {
                'id':'object','type':'Object','notCheckType':true,
                "static": {
                    "longpress": {
                        'id': 'object', 'type': 'Object', 'notCheckType': true,
                        "static": {
                            "requiredTouches": {'id': 'var', 'type': 'int'},
                            "msThresh": {'id': 'var', 'type': 'int'},
                            "triggerStartPhase": {'id': 'var', 'type': 'Boolean'},
                        },
                    },
                    "swipe": {
                        'id': 'const', 'type': 'Object', 'notCheckType': true,
                        "static": {
                            "velocityThresh": {'id': 'var', 'type': 'int'},
                        },
                    },
                    "rotate": {
                        'id': 'const', 'type': 'Object', 'notCheckType': true,
                        "static": {
                            "requiredTouches": {'id': 'var', 'type': 'int'},
                        },
                    },
                },
            },
        },
        'proto':{
            "pageX":{'id':'const','type':'int'},
            "pageY":{'id':'const','type':'int'},
            "offsetX":{'id':'const','type':'int'},
            "offsetY":{'id':'const','type':'int'},
            "screenX":{'id':'const','type':'int'},
            "screenY":{'id':'const','type':'int'},
        }
    },

    'TouchDragEvent':{
        'id':'class', 'type':'TouchDragEvent','inherit':'TouchEvent',
        'static':{
            "TOUCH_DRAG_START":{'id':'const','type':'String'},
            "TOUCH_DRAG_MOVE":{'id':'const','type':'String'},
            "TOUCH_DRAG_END":{'id':'const','type':'String'},
        },
        'proto':{
            "startX":{'id':'const','type':'int'},
            "startY":{'id':'const','type':'int'},
            "moveX":{'id':'const','type':'int'},
            "moveY":{'id':'const','type':'int'},
            "lastMoveX":{'id':'const','type':'int'},
            "lastMoveY":{'id':'const','type':'int'},
            "startDate":{'id':'const','type':'int'},
            "moveDate":{'id':'const','type':'int'},
            "velocity":{'id':'const','type':'float'},
            "held":{'id':'const','type':'int'},
        }
    },

    'TouchPinchEvent':{
        'id':'class', 'type':'TouchPinchEvent','inherit':'TouchEvent',
        'static':{
            "TOUCH_PINCH_START":{'id':'const','type':'String'},
            "TOUCH_PINCH_MOVE":{'id':'const','type':'String'},
            "TOUCH_PINCH_END":{'id':'const','type':'String'},
        },
        'proto':{
            "startX":{'id':'const','type':'int'},
            "startY":{'id':'const','type':'int'},
            "moveX":{'id':'const','type':'int'},
            "moveY":{'id':'const','type':'int'},
            "scale":{'id':'const','type':'int'},
            "previousScale":{'id':'const','type':'float'},
            "moveDistance":{'id':'const','type':'double'},
            "startDistance":{'id':'const','type':'double'},
        }
    },
    'TouchSwipeEvent':{
        'id':'class', 'type':'TouchSwipeEvent','inherit':'TouchEvent',
        'static':{
            "TOUCH_SWIPE_START":{'id':'const','type':'String'},
            "TOUCH_SWIPE_MOVE":{'id':'const','type':'String'},
            "TOUCH_SWIPE_END":{'id':'const','type':'String'},
        },
        'proto':{
            "startX":{'id':'const','type':'int'},
            "startY":{'id':'const','type':'int'},
            "moveX":{'id':'const','type':'int'},
            "moveY":{'id':'const','type':'int'},
            "lastMoveX":{'id':'const','type':'int'},
            "lastMoveY":{'id':'const','type':'int'},
            "startDate":{'id':'const','type':'int'},
            "moveDate":{'id':'const','type':'int'},
            "velocity":{'id':'const','type':'int'},
            "vDistance":{'id':'const','type':'float'},
            "hDistance":{'id':'const','type':'float'},
            "swiped":{'id':'const','type':'int'},
        }
    },
    'DataArray':{
        'id':'class',
        'type':'DataArray',
        'inherit':'Array',
        'proto':{
            'orderBy':{'type':'DataArray','id':'function','param':["Object","String"],'required':[true,false]},
            'sum':{ 'id':'function','type':'int','param':["*"]}
        },
    },
    'DataGrep':{
        'id':'class',
        'type':'DataGrep',
        'inherit':'DataArray',
        'proto':{
            'filter':{'type':'Function','id':'function','param':[]},
            'clean':{'type':'DataGrep','id':'function','param':[]},
            'execute':{'type':'Array','id':'function','param':['*']},
            'range':{'type':'DataGrep','id':'function','param':['String', 'int', 'int', '*']},
            'index':{'type':'DataGrep','id':'function','param':['int', 'int', '*']},
            'eq':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'not':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'gt':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'lt':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'egt':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'elt':{'type':'DataGrep','id':'function','param':['String','Object','*']},
            'like':{'type':'DataGrep','id':'function','param':['String','String','Object','*']},
            'notLike':{'type':'DataGrep','id':'function','param':['String','String','Object','*']},
        },
    },
    'Http':{
        'id':'class',
        'type':'Http',
        'inherit':'EventDispatcher',
        'static':{
            'ACCEPT_XML':{'id':'const','type':'String'},
            'ACCEPT_HTML':{'id':'const','type':'String'},
            'ACCEPT_JSON':{'id':'const','type':'String'},
            'ACCEPT_ALL':{'id':'const','type':'String'},
            'ACCEPT_TEXT':{'id':'const','type':'String'},
            'HEADER_TYPE_URLENCODED':{'id':'const','type':'String'},
            'HEADER_TYPE_FORM_DATA':{'id':'const','type':'String'},
            'HEADER_TYPE_PLAIN':{'id':'const','type':'String'},
            'HEADER_TYPE_JSON':{'id':'const','type':'String'},
            'METHOD_GET':{'id':'const','type':'String'},
            'METHOD_POST':{'id':'const','type':'String'},
            'METHOD_PUT':{'id':'const','type':'String'},
            'METHOD_DELETE':{'id':'const','type':'String'},
            'TYPE_JSONP':{'id':'const','type':'String'},
            'TYPE_JSON':{'id':'const','type':'String'},
            'TYPE_XML':{'id':'const','type':'String'},
            'TYPE_HTML':{'id':'const','type':'String'},
        },
        'proto':{
            'option':{'type':'Object','id':'function','param':['String','Object'], required:[true,false]},
            'abort':{'type':'Boolean','id':'function','param':[]},
            "load":{'type':'Boolean','id':'function','param':['String', 'Object', 'Object'],required:[true,false,false]},
            'setRequestHeader':{'type':'Http','id':'function','param':['String', 'Object']},
            'getResponseHeader':{'type':'String','id':'function','param':['String']},
        },
    },
    'Bindable':{
        'id':'class',
        'type':'Bindable',
        'inherit':'EventDispatcher',
        'static':{},
        'proto':{
            'bind':{'type':'Bindable','id':'function','param':['Object','String','*']},
            'unbind':{'type':'Bindable','id':'function','param':['Object']},
            'property':{'type':'Bindable','id':'function','param':['String', 'Object']},
            'hasProperty':{'type':'Boolean','id':'function','param':['String']},
        },
    },
    'HttpEvent':{
        'id':'class', 'type':'HttpEvent','inherit':'Event',
        'static':{
            "SUCCESS":{'id':'const','type':'String'},
            "ERROR":{'id':'const','type':'String'},
            "CANCELED":{'id':'const','type':'String'},
            "TIMEOUT":{'id':'const','type':'String'},
            "LOAD_START":{'id':'const','type':'String'},
            "PROGRESS":{'id':'const','type':'String'},
        },
        'proto':{
            "data":{'id':'var','type':'Object'},
            "url":{'id':'var','type':'String'},
        }
    },
    'DataSource':{
        'id':'class',
        'type':'DataSource',
        'inherit':'EventDispatcher',
        'proto':{
            'isRemote':{'type':'Boolean','id':'function','param':[]},
            'options':{'type':'DataSource','id':'function','param':['Object']},
            'source':{'type':'DataSource','id':'function','param':['*'],'isFunAccessor':true},

            'parameter':{'type':'Object','id':'function','param':['Object'],'isFunAccessor':true},
            'timeout':{'type':'int','id':'function','param':['int'],'isFunAccessor':true},
            'method':{'type':'String','id':'function','param':['String'],'isFunAccessor':true},
            'dataType':{'type':'String','id':'function','param':['String'],'isFunAccessor':true},

            'pageSize':{'type':'DataSource','id':'function','param':['int'],'isFunAccessor':true},
            'maxBuffer':{'type':'int','id':'function','param':['int'],'isFunAccessor':true},
            'totalPage':{'type':'int','id':'function','param':[]},
            'realSize':{'type':'int','id':'function','param':[]},
            'totalSize':{'type':'int','id':'function','param':[]},
            'grep':{'type':'DataGrep','id':'function','param':[]},
            'filter':{'type':'DataSource','id':'function','param':['*']},
            'current':{'type':'int','id':'function','param':[]},
            'offsetAt':{'type':'int','id':'function','param':['int']},
            'append':{'type':'DataSource','id':'function','param':['Object']},
            'remove':{'type':'DataSource','id':'function','param':['*']},
            'update':{'type':'Boolean','id':'function','param':['*','*']},
            'select':{'type':'DataSource','id':'function','param':['int']},
        },
    },
    'DataSourceEvent':{
        'id':'class', 'type':'DataSourceEvent','inherit':'Event',
        'static':{
            "APPEND":{'id':'const','type':'String'},
            "REMOVE":{'id':'const','type':'String'},
            "UPDATE":{'id':'const','type':'String'},
            "SELECT":{'id':'const','type':'String'},
            "CHANGED":{'id':'const','type':'String'},
        },
        'proto':{
            "data":{'id':'const','type':'Object'},
            "index":{'id':'const','type':'int'},
            "oldValue":{'id':'const','type':'Object'},
            "newValue":{'id':'const','type':'Object'},
            "current":{'id':'const','type':'int'},
            "condition":{'id':'const','type':'Object'},
            "offset":{'id':'const','type':'int'},
            "waiting":{'id':'const','type':'Boolean'},
        }
    },
    'Render': {
        'type': 'Render',
        'id': 'class',
        'inherit':'EventDispatcher',
        'proto': {
            'variable': {type: 'Object', 'id': 'function',param:['*'],required:[true,false]},
            'template': {type: 'String', 'id': 'function',param:['String'],'isFunAccessor':true},
            'fetch': {type: 'String', 'id': 'function',param:[]},
        },
        "xml":{
            'foreach':{name:'String',value:"String"},
            'if': {condition:'String'},
            'elseif': {condition:'String'},
            'else': {},
            'switch': {condition:'String'},
            'case': {condition:'String'},
            'default': {},
            'break':{},
            'do': {},
            'while':{condition:'String'},
            'code':{},
            'script':{},
        },
    },
    'RenderEvent':{
        'id':'class', 'type':'RenderEvent','inherit':'Event',
        'static':{
            "START":{'id':'const','type':'String'},
            "DONE":{'id':'const','type':'String'},
            "REFRESH":{'id':'const','type':'String'},
        },
        'proto':{
            "view":{'id':'const','type':'String'},
            "viewport":{'id':'const','type':'Element'},
            "html":{'id':'const','type':'String'},
        }
    },
    'Locator':{
        'id':'class', 'type':'Locator','inherit':'Object',
        'static':{
            "url":{'id':'function','type':'String'},
            "uri":{'id':'function','type':'String'},
            "path":{'id':'function','type':'String'},
            "host":{'id':'function','type':'String'},
            "port":{'id':'function','type':'String'},
            "pass":{'id':'function','type':'String'},
            "fragment":{'id':'function','type':'String'},
            "query":{'id':'function','type':'String'},
            "toUrl":{'id':'function','type':'String',param:['Object']},
            "create":{'id':'function','type':'Object',param:['String','String'],required:[true,false]},
            "match":{'id':'function','type':'String',param:['*']},
        }
    }
};
module.exports=descriptor;


